### ISSUE TITLE
VSCodeのターミナルでmanage.pyが動かない

### ISSUE THREAD

**Issue by kazweda** [kazweda/djangoauth#22]
```
Found 12 test(s).
Creating test database for alias 'default'...
ImportError: dlopen(/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/_cffi_backend.cpython-311-darwin.so, 0x0002): tried: '/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/_cffi_backend.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/_cffi_backend.cpython-311-darwin.so' (no such file), '/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/_cffi_backend.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
thread '<unnamed>' panicked at 'Python API call failed', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/err/mod.rs:790:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Destroying test database for alias 'default'...
Traceback (most recent call last):
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/manage.py", line 22, in <module>
    main()
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/core/management/commands/test.py", line 24, in run_from_argv
    super().run_from_argv(argv)
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/core/management/commands/test.py", line 68, in handle
    failures = test_runner.run_tests(test_labels)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/test/runner.py", line 1060, in run_tests
    self.run_checks(databases)
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/test/runner.py", line 977, in run_checks
    call_command("check", verbosity=self.verbosity, databases=databases)
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/core/management/commands/check.py", line 76, in handle
    self.check(
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/djangoauth/urls.py", line 10, in <module>
    path('accounts/', include('allauth.urls')),
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/allauth/urls.py", line 19, in <module>
    prov_mod = import_module(provider.get_package() + ".urls")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/allauth/socialaccount/providers/google/urls.py", line 6, in <module>
    urlpatterns = default_urlpatterns(GoogleProvider)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/allauth/socialaccount/providers/oauth2/urls.py", line 7, in default_urlpatterns
    login_view = import_attribute(provider.get_package() + ".views.oauth2_login")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/allauth/utils.py", line 156, in import_attribute
    ret = getattr(importlib.import_module(pkg), attr)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/allauth/socialaccount/providers/google/views.py", line 3, in <module>
    import jwt
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/jwt/__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/jwt/api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/jwt/algorithms.py", line 12, in <module>
    from .utils import (
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/jwt/utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 11, in <module>
    from cryptography.hazmat._oid import ObjectIdentifier
  File "/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/cryptography/hazmat/_oid.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import (
pyo3_runtime.PanicException: Python API call failed
```

**Comment by kazweda** [comment]
```
ImportError: dlopen(/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/_cffi_backend.cpython-311-darwin.so, 0x0002): tried: '/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/_cffi_backend.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/_cffi_backend.cpython-311-darwin.so' (no such file), '/Users/uedakazuaki/Documents/GitHub/djangoauth/venv/lib/python3.11/site-packages/_cffi_backend.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
thread '<unnamed>' panicked at 'Python API call failed'
```
この部分を見ると、
[mach-o file, but is an incompatible architecture (have ‘arm64’, need ‘x86_64’)のエラーを解決するには](https://makicebu.com/mach-o-file-but-is-an-incompatible)
で解決できるのかもしれない。

**Comment by kazweda** [comment]
```
pip uninstall Pillow
arch -arm64 pip install Pillow
```
これでMacOSのターミナルから
```
(venv) % python manage.py test
```
は実行できた。

**Comment by kazweda** [comment]
[AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'](https://stackoverflow.com/questions/76616042/attributeerror-module-pil-image-has-no-attribute-antialias)

Thumbnail表示でエラーになったので、
```
pip uninstall Pillow
arch -arm64 pip install Pillow==9.5.0
```
でひとまず対応。
